version: '3.9'

services:
  jobDb:
    image: postgres:13
    environment:
      - POSTGRES_DB=jobDb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - file-ecosystem
  sftp:
    image: atmoz/sftp
    volumes:
      - C:/Users/brunj/manage_file/upload:/home/foo/manage_file/upload
      - C:/Users/brunj/manage_file/uploaded:/home/foo/manage_file/uploaded
    ports:
      - "2222:22"
    command: foo:pass:1001
    networks:
      - file-ecosystem
  attachment-app:
    container_name: attachment-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:9090"
    networks:
      - file-ecosystem
networks:
  file-ecosystem:
    name: file-ecosystem