version: '3.3'

services:
  job-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=jobDb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  sftp:
    image: atmoz/sftp
    volumes:
      - C:/Users/brunj/manage_file/upload:/home/foo/manage_file/upload
      - C:/Users/brunj/manage_file/uploaded:/home/foo/manage_file/uploaded
    ports:
      - "2222:22"
    command: foo:pass:1001