version: '3.3'

services:
  job-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=jobDb
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data