server:
  port: ${PORT:8080}
spring:
  application:
    name: file-attachment
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: ${USER_DB:sa}
    password: ${PWD_DB:sa}
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  quartz:
    job-store-type: memory
config:
  sftp:
    host: ${SFTP_HOST:localhost}
    port: ${SFTP_PORT:2222}
    user: ${SFTP_USER:foo}
    password: ${SFTP_PWD:pass}
  path:
    local-path: D:/file/upload/
    remote-path: /upload/