server:
  port: ${PORT:8080}
spring:
  application:
    name: file-attachment
  datasource:
    url: jdbc:postgresql://localhost:5432/jobDb
    username: ${USER_DB:root}
    password: ${PWD_DB:root}
  jpa:
    show-sql: true
  quartz:
    job-store-type: memory
config:
  job:
    name: config-job
    param:
      local-path: local-path
      remote-path: remote-path
  sftp:
    host: ${SFTP_HOST:localhost}
    port: ${SFTP_PORT:2222}
    user: ${SFTP_USER:foo}
    password: ${SFTP_PWD:pass}
  path:
    local-path: D:/file/upload/
    remote-path: /upload/
    temp-path: /manage_file/upload/temp/