server:
  port: ${PORT:8080}
spring:
  application:
    name: file-attachment
  quartz:
    job-store-type: memory
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:jobdb
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
api:
  tietoevry:
    user: ${TIETO_USER:provadmin}
    password: ${TIETO_PWD:Provision1234!}
    uri: ${TIETO_URI:http://localhost:8080/api}
config:
  job:
    cron-expression: ${CRON_SCHEDULE:0 0/1 * 1/1 * ? *}
  sftp:
    host: ${SFTP_HOST:localhost}
    port: ${SFTP_PORT:2222}
    user: ${SFTP_USER:foo}
    password: ${SFTP_PWD:pass}
  path:
    local-path: ${FOLDER_LOCAL:D:/file/upload/}
    remote-path: ${FOLDER_REMOTE:/manage_file/upload/}
    temp-path: ${FOLDER_TEMP:/manage_file/upload/temp/}
