server:
  port: ${PORT:8080}
spring:
  application:
    name: file-attachment
  quartz:
    job-store-type: memory
api:
  tietoevry:
    user: ${TIETO_USER:eiradmin}
    password: ${TIETO_PWD:RWl8xxjPYCMMoZPR4HX9}
config:
  job:
    cron-expression: ${CRON_SCHEDULE:0 0/1 * 1/1 * ? *}
  sftp:
    host: ${SFTP_HOST:localhost}
    port: ${SFTP_PORT:2222}
    user: ${SFTP_USER:foo}
    password: ${SFTP_PWD:pass}
  path:
    local-path: ${FOLDER_LOCAL:D:/file/upload/}
    remote-path: ${FOLDER_REMOTE:/manage_file/upload/}
    temp-path: ${FOLDER_TEMP:/manage_file/upload/temp/}
